// CSS
import styles from "../styles/homepage.module.css";
// components
import Head from "next/head";
import Menu from "../components/menu";
import PlayerInfos from "../components/playerInfos";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fifa Project V2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#181648" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <PlayerInfos />
    </div>
  );
}
